### ISSUE TITLE
`initFinishedRe` too restrictive

### ISSUE THREAD

**Issue by sersorrel** [sardinasystems/fleeting-plugin-openstack#14]
The regex `^.*Cloud-init\ v\.\ \d+\.\d+\.\d+\ finished\ at.*$` is too restrictive, and does not match the relevant log line for our OpenStack installation:

```
[   17.405345] cloud-init[1087]: Cloud-init v. 23.4.4-0ubuntu0~22.04.1 finished at Wed, 15 May 2024 15:47:28 +0000. Datasource DataSourceOpenStackLocal [net,ver=2].  Up 17.39 seconds
```

which makes fleeting-plugin-openstack wait the full duration of `boot_time` before marking the instance as ready. (If you set `boot_time` quite high, as a conservative "I don't know exactly how this works and I don't want things to time out", it's not obvious that this is what's happened, since there's no logging for the case where the timeout is reached.)

**Comment by vooon** [comment]
Could you please provide full boot log for your ubuntu?

Like that, which is from Fedora 38: https://github.com/sardinasystems/fleeting-plugin-openstack/blob/main/testdata/console_out.txt
