### ISSUE TITLE
Persist generated private key

### ISSUE THREAD

**Issue by baurmatt** [sardinasystems/fleeting-plugin-openstack#40]
Large parts of our Gitlab Runner fleet are deployed with `MaxBuilds = 100`. For those executors, it would be nice if the generate private key could be persisted and thus reused on Gitlab Runner restarts.

**Comment by baurmatt** [comment]
I'm aware of the possibility to hardcode a SSH private key, but like to have some kind of autogeneration or, better, auto**rotation**

**Comment by baurmatt** [comment]
@vooon Would you be willing to accept a PR if I'd implemented it?

**Comment by vooon** [comment]
@baurmatt it's open for contributions. Just i'd prefer to keep it simple.

**Comment by baurmatt** [comment]
Looked into how the other fleeting plugins solve this:

* [aws](https://gitlab.com/gitlab-org/fleeting/plugins/aws)
  * Static key for all instances
  * Dynamic key for each instance
  * [SendSSHPublicKey](https://docs.aws.amazon.com/ec2-instance-connect/latest/APIReference/API_SendSSHPublicKey.html)/[EC2 Connect](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-linux-inst-eic.html)
* [azure](https://gitlab.com/gitlab-org/fleeting/plugins/azure)
  * No SSH key authentication implemented. Uses username/password possible automatically (?) generated by Azure.
* [digitalocean](https://gitlab.com/alexqrid/fleeting-plugin-digitalocean)
  * Static key for all instances
  * Dynamic key the same for all instances (persisting this dynamic key possible)
  * Upload the public key prior to instance creation. On instance creation, configure the public key
* [gcp](https://gitlab.com/gitlab-org/fleeting/plugins/googlecloud)
  * Static key for all instances
  * Dynamic key for each instance
  * [Metadata-managed SSH connections](https://cloud.google.com/compute/docs/instances/ssh#metadata)
* [hetzner](https://gitlab.com/hetznercloud/fleeting-plugin-hetzner)
  * Static key for all instances
  * Dynamic key the same for all instances 
  * Upload the public key prior to instance creation. On instance creation, configure the public key

**Comment by vooon** [comment]
Looks like you're the one who wants that.
I've implemented key insertion into ingnition simply becaue i do not want to manage dozenth uploaded keys into nova.

Maybe you can simply use badger db with instance uuid = key...

**Comment by baurmatt** [comment]
@vooon Well yes and I've coded the whole friday on an implementation 🙈 While testing my implementation, I've found a new Gitlab Runner (better taskscaler) beta features which tries to solve the exact some problem -> https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersautoscalerstate_storage-section

I guess this feature request can be seen as obsolete :)
